Name:           ros-indigo-eml
Version:        1.8.13
Release:        1%{?dist}
Summary:        ROS eml package

Group:          Development/Libraries
License:        binary only
URL:            http://ethercatmaster.berlios.de/
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin

%description
This is an implementation of the EtherCAT master protocol for the PR2 robot
based on the work done at Flanders' Mechatronics Technology Centre.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jan 13 2015 Devon Ash <dash@clearpathrobotics.com> - 1.8.13-1
- Autogenerated by Bloom

* Tue Jan 13 2015 Devon Ash <dash@clearpathrobotics.com> - 1.8.13-0
- Autogenerated by Bloom

