Name:           ros-melodic-pr2-ethercat-drivers
Version:        1.8.19
Release:        1%{?dist}
Summary:        ROS pr2_ethercat_drivers package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_ethercat_drivers
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-ethercat-hardware
Requires:       ros-melodic-fingertip-pressure
BuildRequires:  ros-melodic-catkin

%description
This stack contains drivers for the ethercat system and the peripherals that
connect to it: motor control boards, fingertip sensors, texture projector, hand
accelerometer.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jul 26 2019 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.8.19-1
- Autogenerated by Bloom

* Tue Mar 12 2019 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.8.18-0
- Autogenerated by Bloom

